# fly.toml app configuration file generated for money-tracker-api on 2023-06-28T19:37:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "money-tracker-api"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
