default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  prepared_statements: false

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { '' } %>
  username: <%= ENV.fetch("DB_USERNAME") { '' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { '' } %>
  prepared_statements: false

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { '' } %>
  username: <%= ENV.fetch("DB_USERNAME") { '' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { '' } %>
  prepared_statements: false

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { '' } %>
  username: <%= ENV.fetch("DB_USERNAME") { '' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOST") { '' } %>
  prepared_statements: false
